name: deploy to aliyun oss
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    # 切代码到 runner
    - uses: actions/checkout@v1
      with:
        submodules: true
    # 使用 node:18
    - name: use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    # npm install
    - name: npm install & build
      run: |
        npm install
        npm run build
      env:
        CI: true
    # 设置阿里云OSS的 id/secret，存储到 github 的 secrets 中
    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    - name: cp files to aliyun
      run: ossutil cp -rf /build oss://ameng-site/
 

