name: Aliyun CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Build project
        run: npm i -g pnpm && pnpm install && pnpm build

      - name: Upload to oss
        uses: chf007/aliyun-oss-upload-action@main
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
        with:
          source-dir: './dist'
          dest-dir: '/'
          bucket: ${{ secrets.OSS_BUCKET }}
          region: 'oss-cn-hangzhou'
